#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=24
#PBS -N 2017_closed_core_diversity
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
core_diversity_analyses.py \
-i ~/2017_03_smb/core_microbiome/core_table_100.biom \
-o ~/2017_03_smb/core_div_coremicrobiome \
-m ~/2017_03_smb/map.tsv \
-t ~/2017_03_smb/closed_otus/97_otus.tree \
-e 564292 \
-a \
-O 12
source deactivate
