#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2017_closed_core_heatmap
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
make_otu_heatmap.py \
-i ~/2017_03_smb/core_microbiome/core_table_100.biom \
-o ~/2017_03_smb/closedcore_heatmap \
-m ~/2017_03_smb/map.tsv
source deactivate
