#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=24
#PBS -N 2018_adonis_denovo_ph
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
compare_categories.py \
--method adonis \
-i ~/2018_02_smb/core_diversity/denovo/bdiv_even765/bray_curtis_dm.txt \
-o ~/2018_02_smb/adonis_denovo_ph \
-m ~/2018_02_smb/map.tsv \
-c SamplePh \
-n 999
source deactivate

output
Call:
adonis(formula = as.dist(qiime.data$distmat) ~ qiime.data$map[[opts$category]],      permutations = opts$num_permutations) 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

                                Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)
qiime.data$map[[opts$category]]  1    0.2455  0.2455  1.0931 0.03757  0.243
Residuals                       28    6.2887  0.2246         0.96243       
Total                           29    6.5342                 1.00000       
adonis_results.txt (END)
