#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=24
#PBS -N 2018_adonis_denovo_depth
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
compare_categories.py \
--method adonis \
-i ~/2018_02_smb/core_diversity/denovo/bdiv_even765/bray_curtis_dm.txt \
-o ~/2018_02_smb/adonis/adonis_denovo_depth \
-m ~/2018_02_smb/map.tsv \
-c SampleDepth \
-n 999
source deactivate
