#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=24
#PBS -N 2018_open_core_diversity
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
core_diversity_analyses.py \
-i ~/2018_02_smb/open_coremicrobiome/core_table_100.biom \
-o ~/2018_02_smb/core_diversity/open_core \
-m ~/2018_02_smb/map.tsv \
-t ~/2018_02_smb/open_otus/97_otus.tree \
-e 605 \
-a \
-O 12
source deactivate
