#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=36
#PBS -N 2018_closed_core_diversity
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
core_diversity_analyses.py \
-i ~/2018_02_smb/closed_otus_greengenes/otu_table.biom \
-o ~/2018_02_smb/core_diversity/closed_otus \
-m ~/2018_02_smb/map.tsv \
-t ~/2018_02_smb/closed_otus_greengenes/97_otus.tree \
-e 605 \
-a \
-O 18
source deactivate




biom summarize-table -i ~/2018_02_smb/closed_otus_greengenes/otu_table.biom
