#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=72
#PBS -N 2018_core_diversity_denovo
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
core_diversity_analyses.py \
-i ~/2018_02_smb/denovo_otus/otu_table.biom \
-o ~/2018_02_smb/core_diversity/denovo_otus \
-m ~/2018_02_smb/map.tsv \
-e 765 \
-a \
-O 36 \
--nonphylogenetic_diversity
source deactivate

scp -r l0123263@login.cirrus.ac.uk:~/2018_02_smb/core_diversity/denovo_otus ~/Users/kristal/Desktop .
