#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=24
#PBS -N 2018_denovo_core_diversity
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
core_diversity_analyses.py \
-i ~/2018_02_smb/
-o ~/2018_02_smb/core_diversity/denovo_otus \
-m ~/2018_02_smb/map.tsv \
-e 
-a \
-O 12 \
--nonphylogenetic_diversity
source deactivate
