#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_closed_core_heatmap
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
make_otu_heatmap.py \
-i ~/2018_02_smb/open_core/core_table_100.biom \
-o ~/2018_02_smb/opencore_heatmap \
-m ~/2018_02_smb/map.tsv
source deactivate
