#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_closed_heatmap
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
make_2d_plots.py \
-i ~/2018_02_smb/core_diversity_analyses_closed_coremicrobiome/bdiv_even605/unweighted_unifrac_pc.txt \
-m ~/2018_02_smb/map.tsv \
-o ~/2018_02_smb/2dplotsclosed/core
source deactivate
