#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=4
#PBS -N 2018_closed_refrence_otus
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
pick_closed_reference_otus.py \
-i ~/2018_02_smb/split_libraries/seqs.fna \
-o ~/2018_02_smb/closed_otus \
-r ~/SILVA_128_QIIME_release/trees/97/97_otus.tre \
-a \
-O 2
source deactivate
