#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=36
#PBS -N 2017_otusgreengenesclosed_refrence_otus
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
pick_closed_reference_otus.py \
-i ~/2017_03_smb/split_libraries/seqs.fna \
-o ~/2017_03_smb/closed_otus \
-a \
-O 18
source deactivate
