#!/bin/bash --login
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2017_closed_core
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
compute_core_microbiome.py \
-i ~/2017_03_smb/closed_otus/otu_table.biom \
-o ~/2017_03_smb/closed_coremicrobiome
source deactivate
