#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2017_split_libraries
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1
split_libraries_fastq.py \
-m ~/2017_03_smb/map.tsv \
-i ~/2017_03_smb/Read1.fastq.gz \
-o ~/2017_03_smb/split_libraries \
-b ~/2017_03_smb/Index.fastq.gz \
-q 19 \
--rev_comp_barcode --rev_comp_mapping_barcodes
source deactivate
